### ISSUE TITLE
Barycenter requirement?

### ISSUE THREAD

**Issue by danieljrichard** [mqzhanglab/BSDE#4]
Hello,
Was trying to install BSDE on MacOS R version 4.2, and ran into the following error:
ERROR: dependency ‘Barycenter’ is not available for package ‘BSDE’

Looking up on CRAN, it appears as though "Barycenter" has been removed.
Are there any workarounds to install BSDE without it?
Thanks,
Daniel

**Comment by richardkwo** [comment]
Hi Daniel, 

A workaround could be installing `Barycenter' from the archive, I suppose?
https://cran.r-project.org/src/contrib/Archive/Barycenter/

**Comment by danieljrichard** [comment]
Yes - thanks! Much appreciated.
